// Developer Express Code Central Example:
// How to allow ComboBoxEdit to select multiple items with the autocomplete feature
// 
// By default, ComboBoxEdit allows you to select one item using the autocomplete
// feature.
// This example provides a way to enable the behavior when the
// autocomplete feature works for multiple item selection. Firstly, it is necessary
// to create a ComboBoxEdit descendant and override the CreateEditStrategy method,
// which should return your own ComboBoxEditStrategy class descendant.
// Then,
// override and implement the ProcessChangeText method, and some more methods to
// enable item auto-searching selection.
// For unimpeded search and selection of
// items without losing input field focus, the set FocusPopupOnOpen property to
// False.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E4226

// Developer Express Code Central Example:
// How to allow ComboBoxEdit to select multiple items with the autocomplete feature
// 
// By default, ComboBoxEdit allows you to select one item using the autocomplete
// feature.
// This example provides a way to enable the behavior when the
// autocomplete feature works for multiple item selection. Firstly, it is necessary
// to create a ComboBoxEdit descendant and override the CreateEditStrategy method,
// which should return your own ComboBoxEditStrategy class descendant.
// Then,
// override and implement the ProcessChangeText method, and some more methods to
// enable item auto-searching selection.
// For unimpeded search and selection of
// items without losing input field focus, the set FocusPopupOnOpen property to
// False.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E4226

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomCheckComboBox.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
